AllCops:
  Include:
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'lib/**/*'
    - '**/Gemfile'
    - '**/Rakefile'
    - !ruby/regexp /old_and_unused\.rb$/

Metrics/LineLength:
  # Change the default 80 chars limit value
  Max: 120
